name: Generate ASCII Artwork

on:
    push

jobs:
    ascii_art:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Generate ASCII Artwork
          run: |
            echo "  _____ _        _   _      _     _"
            echo " / ____| |      | | | |    | |   | |"
            echo "| |    | |      | | | |    | |___| |"
            echo "| |    | |      | | | |    |  ___  |"
            echo "| |____| |____  | | | |____| |   | |"
            echo " \_____|______| |_| |______|_|   |_|"

        - name: Install Cowsay Program
          run: sudo apt-get install cowsay -y

        - name: Execute cowsay CMD
          run: cowsay -f dragon "Run for cover, I am a DRAGON.....WAWR!" >> dragon.txt

        - name: Test File Exists
          run: grep -i "dragon" dragon.txt

        - name: Read File
          run: cat dragon.txt

        - name: List Repo Files
          run: ls -ltra

    