name: WorkFlow One

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Welcome message
      run: echo "The first Github Action Job"

    - name: List files
      run: ls

    - name: Read files
      run: cat README.md